version: '3.9'
services:
  db:
    image: postgres:15
    container_name: argandici-db
    restart: unless-stopped
    env_file:
      - ./.env
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - db-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER}"]
      interval: 10s
      timeout: 5s
      retries: 5

  app:
    build:
      context: .
      dockerfile: Dockerfile
      target: dev
    container_name: argandici-app
    restart: unless-stopped
    env_file:
      - ./.env
    environment:
      DATABASE_URL: "postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:5432/${POSTGRES_DB}?schema=public&pgbouncer=true"
    ports:
      - "3000:3000"
      - "5555:5555"
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - ./:/app
    entrypoint: >
      sh -c "npx prisma migrate deploy &&
             npx nuxt dev --hostname 0.0.0.0 --port 3000"

volumes:
  db-data:
  node_modules:
